apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cnrm.cloud.google.com/version: 0.0.0-dev
  creationTimestamp: null
  labels:
    cnrm.cloud.google.com/managed-by-kcc: "true"
    cnrm.cloud.google.com/system: "true"
  name: storageanywherecaches.storage.cnrm.cloud.google.com
spec:
  group: storage.cnrm.cloud.google.com
  names:
    categories:
    - gcp
    kind: StorageAnywhereCache
    listKind: StorageAnywhereCacheList
    plural: storageanywherecaches
    shortNames:
    - gcpstorageanywherecache
    - gcpstorageanywherecaches
    singular: storageanywherecache
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: When 'True', the most recent reconcile of the resource succeeded
      jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: Ready
      type: string
    - description: The reason for the value in 'Ready'
      jsonPath: .status.conditions[?(@.type=='Ready')].reason
      name: Status
      type: string
    - description: The last transition time for the value in 'Status'
      jsonPath: .status.conditions[?(@.type=='Ready')].lastTransitionTime
      name: Status Age
      type: date
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: StorageAnywhereCache is the Schema for the StorageAnywhereCache
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: StorageAnywhereCacheSpec defines the desired state of StorageAnywhereCache
            properties:
              admissionPolicy:
                description: 'Cache admission policy. Valid policies includes: `admit-on-first-miss`
                  and `admit-on-second-miss`. Defaults to `admit-on-first-miss`.'
                type: string
              bucketRef:
                description: Immutable. The bucketRef
                oneOf:
                - not:
                    required:
                    - external
                  required:
                  - name
                - not:
                    anyOf:
                    - required:
                      - name
                    - required:
                      - namespace
                  required:
                  - external
                properties:
                  external:
                    description: The StorageBucket selfLink, when not managed by Config
                      Connector.
                    type: string
                  name:
                    description: The `name` field of a `StorageBucket` resource.
                    type: string
                  namespace:
                    description: The `namespace` field of a `StorageBucket` resource.
                    type: string
                type: object
              desiredState:
                description: The desired state of the cache, possible values include
                  "running", "disabled", "paused", It defaults to "running". It can
                  be used to control the runtime behavior of cache.
                type: string
              resourceID:
                description: The StorageAnywhereCache ID. If not given, the metadata.name
                  will be used.
                type: string
              ttl:
                description: Cache entry TTL (ranges between 1h to 7d). This is a
                  cache-level config that defines how long a cache entry can live.
                  Defaults to 86400s TTL must be in whole seconds.
                type: string
              zone:
                description: Immutable. The zone in which the cache instance is running.
                  For example, us-central1-a.
                type: string
            required:
            - bucketRef
            - zone
            type: object
          status:
            description: StorageAnywhereCacheStatus defines the config connector machine
              state of StorageAnywhereCache
            properties:
              conditions:
                description: Conditions represent the latest available observations
                  of the object's current state.
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition.
                      type: string
                    reason:
                      description: Unique, one-word, CamelCase reason for the condition's
                        last transition.
                      type: string
                    status:
                      description: Status is the status of the condition. Can be True,
                        False, Unknown.
                      type: string
                    type:
                      description: Type is the type of the condition.
                      type: string
                  type: object
                type: array
              externalRef:
                description: A unique specifier for the StorageAnywhereCache resource
                  in GCP.
                type: string
              observedGeneration:
                description: ObservedGeneration is the generation of the resource
                  that was most recently observed by the Config Connector controller.
                  If this is equal to metadata.generation, then that means that the
                  current reported status reflects the most recent desired state of
                  the resource.
                format: int64
                type: integer
              observedState:
                description: ObservedState is the state of the resource as most recently
                  observed in GCP.
                properties:
                  createTime:
                    description: Output only. Time when Anywhere cache instance is
                      allocated.
                    type: string
                  pendingUpdate:
                    description: Output only. True if there is an active update operation
                      against this cache instance. Subsequential update requests will
                      be rejected if this field is true. Output only.
                    type: boolean
                  state:
                    description: Output only. Cache state including RUNNING, CREATING,
                      DISABLED and PAUSED.
                    type: string
                  updateTime:
                    description: Output only. Time when Anywhere cache instance is
                      last updated, including creation.
                    type: string
                type: object
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
